In [4]:
import numpy as np

In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[10, 20], [30, 40]])
C = A + B
print(C)

[[11 22]
 [33 44]]


In [7]:
m1 = np.zeros((3, 2, 4))
print('m1.dtype: ', m1.dtype)
print('m1.shape: ', m1.shape)
print('m1.size: ', m1.size)

m1.dtype:  float64
m1.shape:  (3, 2, 4)
m1.size:  24
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [9]:
m2 = np.random.rand(2, 3, 4, 5)
print('max(m2): ',np.max(m2))
print('sum(m2): ', np.sum(m2))

m2.shape:  (2, 3, 4, 5)
max(m2):  0.9922611073777815
sum(m2):  58.97711152070815


In [10]:
v1 = np.random.randn(100)
v2 = np.random.randn(1000)
print('mean(v1):', np.mean(v1))
print('std(v1): ', np.std(v1))
print()
print('mean(v2):', np.mean(v2))
print('std(v2): ', np.std(v2))

mean(v1): 0.06805316208654814
std(v1):  1.0533549689835606

mean(v2): 0.03324387244597899
std(v2):  1.024074761103349


In [21]:
v3 = np.arange(20, 51)
print('reverse 20-50:\n', v3[::-1])

reverse 20-50:
 [50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20]


In [14]:
v4 = np.arange(1, 28)
v4 = v4.reshape(3, 3, 3)
print(v4)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [19]:
m3 = np.random.randint(9, size=(5, 6))
m4 = np.random.randint(9, size=(6, 3))
print('dot(m3, m4):\n', np.dot(m3, m4))

dot(m3, m4):
 [[126  50  56]
 [144  61  95]
 [ 98  61  90]
 [155  62 118]
 [113  53  84]]


In [23]:
v5 = np.random.randint(100, size=20)
bool_indices = (v5 > 50)
print('new vector: ', v5[bool_indices])

v5:  [40 34 25 25 94 39 23 11 47 63 92 18 70 42 95 39 96 89 17 72]
new vector:  [94 63 92 70 95 96 89 72]
